---
name: "\U0001F680 Feature request"
about: Sugira uma ideia para este projeto

---


**Sua solicitação de recurso está relacionada a um problema? Por favor, descreva.**
Por favor, descreva o problema que você está tentando resolver.

**Descreva a solução que você gostaria **
Por favor, descreva o comportamento desejado.

**Descreva as alternativas que você considerou**
Por favor, descreva as soluções ou recursos alternativos que você considerou.
