import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Hero from "@/components/hero";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RoboStage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <Hero />
        {children}
      </body>
    </html>
  );
}
