import { CategoryDefinition, EmpathyCategory, EmpathyMap, NoteColor } from '@/types/EmpathyMap.types';

export const CATEGORIES: Record<EmpathyCategory, CategoryDefinition> = {
  thinks: {
    id: 'thinks',
    title: 'O que Pensa?',
    subtitle: 'Preocupações e pensamentos que talvez não expresse.',
    guidingQuestion: 'O que passa pela mente da persona? Crenças, aspirações e dúvidas silenciosas.',
    accentColor: '#3B82F6',
    bgLight: 'bg-blue-50/60',
    borderLight: 'border-blue-200/80',
    badgeBg: 'text-blue-700 bg-blue-100',
    iconName: 'Brain',
  },
  feels: {
    id: 'feels',
    title: 'O que Sente?',
    subtitle: 'Emoções, medos e estados de espírito.',
    guidingQuestion: 'Quais emoções guiam o usuário? O que o deixa ansioso, frustrado ou animado?',
    accentColor: '#EC4899',
    bgLight: 'bg-pink-50/60',
    borderLight: 'border-pink-200/80',
    badgeBg: 'text-pink-700 bg-pink-100',
    iconName: 'Heart',
  },
  says: {
    id: 'says',
    title: 'O que Diz?',
    subtitle: 'Citações verbais e declarações diretas.',
    guidingQuestion: 'O que o usuário verbaliza em conversas, entrevistas ou feedbacks?',
    accentColor: '#10B981',
    bgLight: 'bg-emerald-50/60',
    borderLight: 'border-emerald-200/80',
    badgeBg: 'text-emerald-700 bg-emerald-100',
    iconName: 'MessageSquareQuote',
  },
  does: {
    id: 'does',
    title: 'O que Faz?',
    subtitle: 'Ações práticas, rotinas e hábitos.',
    guidingQuestion: 'Quais comportamentos observáveis o usuário realiza na prática?',
    accentColor: '#8B5CF6',
    bgLight: 'bg-purple-50/60',
    borderLight: 'border-purple-200/80',
    badgeBg: 'text-purple-700 bg-purple-100',
    iconName: 'Activity',
  },
  pains: {
    id: 'pains',
    title: 'Dores & Frustrações',
    subtitle: 'Obstáculos, atritos e receios.',
    guidingQuestion: 'Quais são as principais barreiras, atritos ou medos do usuário?',
    accentColor: '#EF4444',
    bgLight: 'bg-rose-50/60',
    borderLight: 'border-rose-200/80',
    badgeBg: 'text-rose-700 bg-rose-100',
    iconName: 'AlertTriangle',
  },
  gains: {
    id: 'gains',
    title: 'Necessidades & Ganhos',
    subtitle: 'Objetivos, desejos e critérios de sucesso.',
    guidingQuestion: 'O que o usuário deseja alcançar? Quais resultados trariam real alívio?',
    accentColor: '#F59E0B',
    bgLight: 'bg-amber-50/60',
    borderLight: 'border-amber-200/80',
    badgeBg: 'text-amber-700 bg-amber-100',
    iconName: 'Sparkles',
  },
};

export const NOTE_COLORS: Record<NoteColor, {
  name: string;
  bg: string;
  text: string;
  border: string;
  dot: string;
  hover: string;
}> = {
  yellow: {
    name: 'Amarelo',
    bg: 'bg-[#FEF9C3]',
    text: 'text-amber-950',
    border: 'border-amber-300',
    dot: '#EAB308',
    hover: 'hover:bg-[#FEF08A]',
  },
  emerald: {
    name: 'Menta',
    bg: 'bg-[#DCFCE7]',
    text: 'text-emerald-950',
    border: 'border-emerald-300',
    dot: '#10B981',
    hover: 'hover:bg-[#BBF7D0]',
  },
  pink: {
    name: 'Rosa',
    bg: 'bg-[#FFE4E6]',
    text: 'text-rose-950',
    border: 'border-rose-300',
    dot: '#F43F5E',
    hover: 'hover:bg-[#FECDD3]',
  },
  blue: {
    name: 'Azul',
    bg: 'bg-[#E0F2FE]',
    text: 'text-sky-950',
    border: 'border-sky-300',
    dot: '#0EA5E9',
    hover: 'hover:bg-[#BAE6FD]',
  },
  purple: {
    name: 'Lavanda',
    bg: 'bg-[#F3E8FF]',
    text: 'text-purple-950',
    border: 'border-purple-300',
    dot: '#A855F7',
    hover: 'hover:bg-[#E9D5FF]',
  },
  amber: {
    name: 'Pêssego',
    bg: 'bg-[#FFEDD5]',
    text: 'text-orange-950',
    border: 'border-orange-300',
    dot: '#F97316',
    hover: 'hover:bg-[#FED7AA]',
  },
  slate: {
    name: 'Neutro',
    bg: 'bg-[#F1F5F9]',
    text: 'text-slate-900',
    border: 'border-slate-300',
    dot: '#64748B',
    hover: 'hover:bg-[#E2E8F0]',
  },
};

export const COMMON_TAGS = [
  'Urgente',
  'Citação Direta',
  'Oportunidade',
  'Mobile',
  'Segurança',
  'Simplicidade',
];

export const INITIAL_MAPS: EmpathyMap[] = [
  {
    id: "map-equipe-fll",
    title: "Equipe FLL - Preparação para o Torneio",
    description:
      "Mapeamento de empatia de uma equipe de estudantes que organiza sua preparação para a FIRST LEGO League Challenge.",
    createdAt: 1760000000000,
    updatedAt: 1760100000000,
    persona: {
      id: "persona-equipe-fll",
      name: "Ana Oliveira",
      role: "Estudante competidora e líder de equipe",
      segment: "FIRST LEGO League Challenge",
      demographics: "14 anos · Equipe escolar de robótica",
      quote:
        "Quero que todo mundo saiba o que precisa fazer e que a gente consiga mostrar tudo o que aprendeu no torneio.",
      context:
        "Participa dos encontros de robótica no contraturno escolar. Ajuda a organizar tarefas, acompanhar os testes do robô e preparar a equipe para a apresentação. Tem dificuldade para conciliar as atividades e garantir que todos estejam alinhados.",
      avatarUrl: "",
    },
    notes: [
      {
        id: "fll-team-1",
        category: "thinks",
        text: "Será que vamos conseguir terminar o robô, o Projeto de Inovação e a preparação para o Core Values a tempo?",
        color: "blue",
        author: "Entrevista",
        votes: 6,
        sentiment: "negative",
        tags: ["Organização", "Prazo"],
        createdAt: 1760001000000,
      },
      {
        id: "fll-team-2",
        category: "thinks",
        text: "Precisamos registrar nossas decisões e aprendizados para não esquecer por que fizemos cada mudança.",
        color: "blue",
        author: "Workshop",
        votes: 8,
        sentiment: "positive",
        tags: ["Caderno de Engenharia", "Documentação"],
        createdAt: 1760002000000,
      },
      {
        id: "fll-team-3",
        category: "feels",
        text: "Fica ansiosa quando percebe que algumas tarefas estão atrasadas e a data do torneio está chegando.",
        color: "pink",
        author: "Entrevista",
        votes: 7,
        sentiment: "negative",
        tags: ["Prazo", "Urgente"],
        createdAt: 1760003000000,
      },
      {
        id: "fll-team-4",
        category: "feels",
        text: "Sente orgulho quando a equipe resolve um problema em conjunto, mesmo depois de várias tentativas.",
        color: "emerald",
        author: "Observação",
        votes: 9,
        sentiment: "positive",
        tags: ["Core Values", "Colaboração"],
        createdAt: 1760004000000,
      },
      {
        id: "fll-team-5",
        category: "says",
        text: '"A gente precisa anotar o que funcionou no treino de hoje para conseguir repetir depois."',
        color: "yellow",
        author: "Entrevista",
        votes: 8,
        sentiment: "positive",
        tags: ["Citação Direta", "Registro"],
        createdAt: 1760005000000,
      },
      {
        id: "fll-team-6",
        category: "says",
        text: '"Não adianta só o robô funcionar. Todo mundo precisa entender o projeto e conseguir explicar o que fez."',
        color: "yellow",
        author: "Workshop",
        votes: 7,
        sentiment: "positive",
        tags: ["Apresentação", "Equipe"],
        createdAt: 1760006000000,
      },
      {
        id: "fll-team-7",
        category: "does",
        text: "Divide tarefas entre programação, construção, pesquisa e preparação das apresentações.",
        color: "purple",
        author: "Observação",
        votes: 6,
        sentiment: "neutral",
        tags: ["Planejamento", "Tarefas"],
        createdAt: 1760007000000,
      },
      {
        id: "fll-team-8",
        category: "does",
        text: "Registra resultados dos testes, tira fotos das montagens e revisa as anotações antes dos encontros.",
        color: "purple",
        author: "Observação",
        votes: 7,
        sentiment: "positive",
        tags: ["Caderno de Engenharia", "Testes"],
        createdAt: 1760008000000,
      },
      {
        id: "fll-team-9",
        category: "pains",
        text: "As informações ficam espalhadas entre cadernos, mensagens e arquivos, dificultando encontrar decisões anteriores.",
        color: "pink",
        author: "Entrevista",
        votes: 9,
        sentiment: "negative",
        tags: ["Organização", "Urgente"],
        createdAt: 1760009000000,
      },
      {
        id: "fll-team-10",
        category: "pains",
        text: "Algumas pessoas concentram muitas tarefas enquanto outras não sabem como contribuir.",
        color: "pink",
        author: "Observação",
        votes: 8,
        sentiment: "negative",
        tags: ["Colaboração", "Divisão de tarefas"],
        createdAt: 1760010000000,
      },
      {
        id: "fll-team-11",
        category: "gains",
        text: "Ter um espaço compartilhado para registrar tarefas, reuniões, decisões, testes e próximos passos.",
        color: "emerald",
        author: "Ideação",
        votes: 10,
        sentiment: "positive",
        tags: ["Oportunidade", "Gestão"],
        createdAt: 1760011000000,
      },
      {
        id: "fll-team-12",
        category: "gains",
        text: "Conseguir visualizar a evolução da equipe durante a temporada e recuperar facilmente os aprendizados.",
        color: "emerald",
        author: "Workshop",
        votes: 8,
        sentiment: "positive",
        tags: ["Evolução", "Documentação"],
        createdAt: 1760012000000,
      },
    ],
  },

  {
    id: "map-fll-robot",
    title: "Lucas Mendes - Construção e Programação do Robô",
    description:
      "Mapeamento de empatia de um competidor que desenvolve, programa e testa o robô para as missões da temporada.",
    createdAt: 1760200000000,
    updatedAt: 1760300000000,
    persona: {
      id: "persona-lucas-fll",
      name: "Lucas Mendes",
      role: "Estudante responsável pela programação",
      segment: "Robótica Educacional / FLL Challenge",
      demographics: "13 anos · Equipe de robótica escolar",
      quote:
        "Quero descobrir por que o robô errou e melhorar o programa sem precisar começar tudo de novo.",
      context:
        "Participa da construção e programação do robô LEGO Education. Trabalha com outros estudantes para executar missões da mesa de competição. Enfrenta dificuldades para reproduzir erros, comparar resultados e entender o efeito de cada alteração no programa.",
      avatarUrl: "",
    },
    notes: [
      {
        id: "fll-robot-1",
        category: "thinks",
        text: "Será que o erro está no programa, na montagem do robô ou na posição inicial na mesa?",
        color: "blue",
        author: "Entrevista",
        votes: 9,
        sentiment: "neutral",
        tags: ["Depuração", "Testes"],
        createdAt: 1760201000000,
      },
      {
        id: "fll-robot-2",
        category: "thinks",
        text: "Se eu alterar várias coisas ao mesmo tempo, não vou saber qual mudança realmente melhorou o resultado.",
        color: "blue",
        author: "Observação",
        votes: 8,
        sentiment: "negative",
        tags: ["Experimentação", "Programação"],
        createdAt: 1760202000000,
      },
      {
        id: "fll-robot-3",
        category: "feels",
        text: "Fica frustrado quando o robô executa uma missão corretamente durante o treino, mas falha na tentativa seguinte.",
        color: "pink",
        author: "Entrevista",
        votes: 8,
        sentiment: "negative",
        tags: ["Confiabilidade", "Urgente"],
        createdAt: 1760203000000,
      },
      {
        id: "fll-robot-4",
        category: "feels",
        text: "Sente satisfação quando consegue identificar a causa de um erro e reproduzir o resultado esperado.",
        color: "emerald",
        author: "Observação",
        votes: 7,
        sentiment: "positive",
        tags: ["Aprendizagem", "Conquista"],
        createdAt: 1760204000000,
      },
      {
        id: "fll-robot-5",
        category: "says",
        text: '"Vamos repetir o teste mais algumas vezes antes de dizer que essa versão está pronta."',
        color: "yellow",
        author: "Entrevista",
        votes: 9,
        sentiment: "positive",
        tags: ["Citação Direta", "Validação"],
        createdAt: 1760205000000,
      },
      {
        id: "fll-robot-6",
        category: "does",
        text: "Executa a mesma missão várias vezes, mede o desempenho e ajusta parâmetros como velocidade, potência e tempo.",
        color: "purple",
        author: "Observação",
        votes: 8,
        sentiment: "neutral",
        tags: ["Testes", "Calibração"],
        createdAt: 1760206000000,
      },
      {
        id: "fll-robot-7",
        category: "does",
        text: "Salva versões dos programas e registra quais alterações foram feitas antes de cada teste.",
        color: "purple",
        author: "Workshop",
        votes: 7,
        sentiment: "positive",
        tags: ["Programação", "Histórico"],
        createdAt: 1760207000000,
      },
      {
        id: "fll-robot-8",
        category: "pains",
        text: "Não consegue comparar os resultados de diferentes versões porque os testes anteriores não foram registrados de maneira consistente.",
        color: "pink",
        author: "Entrevista",
        votes: 9,
        sentiment: "negative",
        tags: ["Documentação", "Urgente"],
        createdAt: 1760208000000,
      },
      {
        id: "fll-robot-9",
        category: "pains",
        text: "Pequenas diferenças na posição do robô, nas rodas ou nas condições da mesa alteram o resultado da missão.",
        color: "pink",
        author: "Observação",
        votes: 8,
        sentiment: "negative",
        tags: ["Precisão", "Repetibilidade"],
        createdAt: 1760209000000,
      },
      {
        id: "fll-robot-10",
        category: "gains",
        text: "Ter um histórico de execuções com configurações, pontuações, observações e resultados de cada teste.",
        color: "emerald",
        author: "Ideação",
        votes: 10,
        sentiment: "positive",
        tags: ["Oportunidade", "LabTest"],
        createdAt: 1760210000000,
      },
      {
        id: "fll-robot-11",
        category: "gains",
        text: "Identificar quais missões apresentam resultados mais consistentes e priorizar melhorias com base em evidências.",
        color: "emerald",
        author: "Workshop",
        votes: 9,
        sentiment: "positive",
        tags: ["Desempenho", "Estratégia"],
        createdAt: 1760211000000,
      },
    ],
  },

  {
    id: "map-fll-innovation",
    title: "Beatriz Costa - Projeto de Inovação",
    description:
      "Mapeamento de empatia de uma estudante que pesquisa um problema real, desenvolve uma solução inovadora e prepara sua apresentação.",
    createdAt: 1760400000000,
    updatedAt: 1760500000000,
    persona: {
      id: "persona-beatriz-fll",
      name: "Beatriz Costa",
      role: "Estudante pesquisadora e responsável pelo projeto",
      segment: "Projeto de Inovação / FLL Challenge",
      demographics: "14 anos · Equipe escolar de robótica",
      quote:
        "A gente não quer só apresentar uma ideia legal. Queremos criar algo que realmente ajude alguém.",
      context:
        "Participa da investigação de um problema da comunidade, pesquisa soluções existentes, conversa com possíveis usuários e trabalha no desenvolvimento da proposta da equipe. Precisa organizar evidências, registrar a evolução da ideia e explicar o impacto da solução.",
      avatarUrl: "",
    },
    notes: [
      {
        id: "fll-innovation-1",
        category: "thinks",
        text: "Como podemos ter certeza de que estamos resolvendo um problema real e não apenas imaginando o que as pessoas precisam?",
        color: "blue",
        author: "Entrevista",
        votes: 9,
        sentiment: "neutral",
        tags: ["Pesquisa", "Usuário"],
        createdAt: 1760401000000,
      },
      {
        id: "fll-innovation-2",
        category: "thinks",
        text: "Precisamos mostrar o que já existe, o que nossa solução tem de diferente e por que ela pode funcionar.",
        color: "blue",
        author: "Workshop",
        votes: 8,
        sentiment: "positive",
        tags: ["Inovação", "Evidências"],
        createdAt: 1760402000000,
      },
      {
        id: "fll-innovation-3",
        category: "feels",
        text: "Fica insegura quando precisa apresentar uma proposta que ainda não foi validada com pessoas de fora da equipe.",
        color: "pink",
        author: "Entrevista",
        votes: 7,
        sentiment: "negative",
        tags: ["Validação", "Urgente"],
        createdAt: 1760403000000,
      },
      {
        id: "fll-innovation-4",
        category: "feels",
        text: "Sente entusiasmo quando uma pessoa que enfrenta o problema confirma que a ideia pode ser útil.",
        color: "emerald",
        author: "Observação",
        votes: 8,
        sentiment: "positive",
        tags: ["Impacto", "Validação"],
        createdAt: 1760404000000,
      },
      {
        id: "fll-innovation-5",
        category: "says",
        text: '"Antes de escolher a solução, precisamos ouvir quem vive esse problema todos os dias."',
        color: "yellow",
        author: "Entrevista",
        votes: 9,
        sentiment: "positive",
        tags: ["Citação Direta", "Pesquisa"],
        createdAt: 1760405000000,
      },
      {
        id: "fll-innovation-6",
        category: "says",
        text: '"O que aprendemos com os testes precisa aparecer na versão final do projeto."',
        color: "yellow",
        author: "Workshop",
        votes: 7,
        sentiment: "positive",
        tags: ["Citação Direta", "Iteração"],
        createdAt: 1760406000000,
      },
      {
        id: "fll-innovation-7",
        category: "does",
        text: "Pesquisa soluções existentes, consulta fontes confiáveis, entrevista pessoas e reúne evidências sobre o problema.",
        color: "purple",
        author: "Observação",
        votes: 8,
        sentiment: "neutral",
        tags: ["Pesquisa", "Fontes"],
        createdAt: 1760407000000,
      },
      {
        id: "fll-innovation-8",
        category: "does",
        text: "Cria protótipos, coleta opiniões, registra mudanças e divide a preparação da apresentação entre os integrantes.",
        color: "purple",
        author: "Observação",
        votes: 8,
        sentiment: "positive",
        tags: ["Prototipagem", "Colaboração"],
        createdAt: 1760408000000,
      },
      {
        id: "fll-innovation-9",
        category: "pains",
        text: "É difícil encontrar em um só lugar as fontes de pesquisa, os registros das entrevistas e as versões anteriores da solução.",
        color: "pink",
        author: "Entrevista",
        votes: 9,
        sentiment: "negative",
        tags: ["Organização", "Documentação"],
        createdAt: 1760409000000,
      },
      {
        id: "fll-innovation-10",
        category: "pains",
        text: "A equipe tem dificuldade para explicar claramente como a solução evoluiu a partir das pesquisas e dos testes realizados.",
        color: "pink",
        author: "Workshop",
        votes: 8,
        sentiment: "negative",
        tags: ["Comunicação", "Evidências"],
        createdAt: 1760410000000,
      },
      {
        id: "fll-innovation-11",
        category: "gains",
        text: "Organizar problema, público impactado, pesquisa, especialistas consultados, protótipos, testes e melhorias em uma sequência clara.",
        color: "emerald",
        author: "Ideação",
        votes: 10,
        sentiment: "positive",
        tags: ["Oportunidade", "Caderno de Engenharia"],
        createdAt: 1760411000000,
      },
      {
        id: "fll-innovation-12",
        category: "gains",
        text: "Apresentar uma solução fundamentada em pesquisa, aprimorada com feedback e acompanhada de evidências do impacto potencial.",
        color: "emerald",
        author: "Workshop",
        votes: 9,
        sentiment: "positive",
        tags: ["Impacto", "Apresentação"],
        createdAt: 1760412000000,
      },
    ],
  },
];
